### ISSUE TITLE
STM32 is not basic component

### ISSUE THREAD

**Issue by fmunozs** [jberclaz/modelh#1]
I am trying to follow your guide, thanks!

It seems now that the STM32 is part of the extended component list

![image](https://github.com/jberclaz/modelh/assets/1041604/81e58104-3247-4b0f-87e1-f93cc66259b7)

**Comment by jberclaz** [comment]
Looks like they have moved it to extended. That is unfortunate. It should still work, but will be a bit more expensive.

**Comment by jberclaz** [comment]
Actually, even with the move to Exteneded Parts, it's still cheaper now than when I bought it a year ago.

**Comment by fmunozs** [comment]
Just an update, my boards arrived  from pcbway a couple weeks ago, and I was able to flash it following your instructions, everything went very smooth! I noticed that ISO layout was not supported (the key next to left shift not being registered), I opened a PR to vial adding support for it https://github.com/vial-kb/vial-qmk/pull/688 and I was able to swap 2 SSKs :)  

Too bad I just read recently that the project is no longer supported

**Comment by jberclaz** [comment]
Glad to hear it worked! Thanks for the feedback.
