### ISSUE TITLE
The Vial Firmware attached to this repo is outdated.

### ISSUE THREAD

**Issue by lvisintini** [jberclaz/modelh#3]
I tried it first and realized that it only allowed for and ANSI layout.

Compiling your own form scratch allows you to control whether you have a ISO enter and a Split left shift.

Maybe that file could be updated?
I assume that the QMK firmware is also out of date if the VIAL QMK one is. Maybe that needs updating too?

**Comment by jberclaz** [comment]
Good point, I added recently compiled firmware to the "Releases".
